export { default as H1 } from "./H1";
export { default as H2 } from "./H2";
export { default as H3 } from "./H3";
export { default as h4 } from "./H4";
export { default as H5 } from "./H5";
export { default as H6 } from "./H6";
export { default as Paragraph } from "./Paragraph";
export { default as Emphasis } from "./Emphasis";
export { default as Small } from "./Small";